# Generated by Django 5.0.9 on 2024-10-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
    ]
