# Generated by Django 5.0.9 on 2024-10-05 23:16
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_trigram_ext'),
    ]

    operations = [
        TrigramExtension()
    ]
