# Generated by Django 5.0.9 on 2024-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for your upload', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Enter some text', null=True)),
                ('video_link', models.URLField(blank=True, help_text='Paste a video link (YouTube, Vimeo, etc.)', null=True)),
                ('picture', models.ImageField(blank=True, help_text='Upload a picture', null=True, upload_to='pictures/')),
                ('file', models.FileField(blank=True, help_text='Upload a file', null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
