# Generated by Django 5.0.10 on 2024-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content', max_length=255)),
                ('text', models.TextField(blank=True, help_text='Text content', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('video_link', models.URLField(blank=True, help_text='YouTube or Vimeo video URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
